---
title: "Practical Machine Learning Project"
author: "lianrui"
date: "2017年9月28日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background
## Executive summary
## Getting the data

```{r}
library(caret)
```


```{r, create data directory}
if (!file.exists("data")) {
    dir.create("data")
}
```


```{r, downloading data, echo=FALSE}
urlTrain <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
urlTest <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(urlTrain, destfile = "./data/pml-training.csv", method = "curl")
download.file(urlTest, destfile = "./data/pml-testing.csv", method = "curl")
```


```{r, Read data into R}
pmlTrain <- read.table("./data/pml-training.csv", header = TRUE, sep = ",")
pmlTest <- read.table("./data/pml-testing.csv", header = TRUE, sep = ",")
dim(pmlTrain);dim(pmlTest);table(pmlTrain$classe)
```


### data preparation: zero, near-near removing.  
```{r}
set.seed(38360)
nzvTrain <- nearZeroVar(pmlTrain)
nzvTest <- nearZeroVar(pmlTest)
nzv <- unique(c(nzvTrain, nzvTest))
rDat <- pmlTrain[, -nzv]
test20 <- pmlTest[, -nzv]
rDatCls <- as.factor(rDat$classe)
rDat <- rDat[, -c(2, 5)]
test20 <- test20[, -c(2, 5)]
```


### feature selection using correlation. 
```{r}
set.seed(38360)
rDatCor <- cor(rDat[,-57])
highlyCorrelated <- findCorrelation(rDatCor, cutoff=0.75)
rDatFinal <- rDat[, -highlyCorrelated]
dim(rDatFinal)
test20Final <- test20[, -highlyCorrelated]
dim(test20Final)
names(rDatFinal); names(test20Final)
```

```{r}
for (i in 1:34){
        fplot <- featurePlot(x=rDatFinal[,i],
            y = rDatFinal$classe,
            plot="density", 
            alpha = 0.8)
        print(fplot)
        
}
```




```{r}
rDatFinal <- rDatFinal[, -c(1, 2, 3, 4, 23, 28, 29)]
dim(rDatFinal)
test20Final <- test20Final[, -c(1, 2, 3, 4, 23, 28, 29)]
dim(test20Final)
```


### data partition
```{r}
inTrain <- createDataPartition(rDatFinal$classe, p = 0.75, list = FALSE)
train <- rDatFinal[inTrain,]
test <- rDatFinal[-inTrain,]
dim(train)
```


```{r}
fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 5,
                           ## repeated ten times
                           repeats = 10)
```


### random forest. 
```{r}
rf_Fit <- train(classe ~ ., data = train, 
                 method = "rf", 
                 trControl = fitControl,
                 proximity = TRUE)
rf_Fit

```



### the variable importance. 
```{r}
vImp <- varImp(rf_Fit)
order(vImp$importance)
```


### evaluate and test the test dataset. 
```{r}
predictions <- predict(rf_Fit, newdata = test[, -35])

```


```{r}
table(test$classe)
confusionMatrix(predictions, test$classe)
```

### predict the 20 samples. 
```{r}
str(test20Final)
test20predict <- predict(rf_Fit, newdata = test20Final[, -28])
test20predict

```


