---
title: "Practical Machine Learning Project"
author: "lianrui"
date: "2017年9月28日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Background
## Executive summary
## Getting the data

```{r, create data directory}
if (!file.exists("data")) {
    dir.create("data")
}
```


```{r, downloading data, echo=FALSE}
urlTrain <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
urlTest <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
download.file(urlTrain, destfile = "./data/pml-training.csv", method = "curl")
download.file(urlTest, destfile = "./data/pml-testing.csv", method = "curl")
```


```{r, Read data into R}
pmlTrain <- read.table("./data/pml-training.csv", header = TRUE, sep = ",")
pmlTest <- read.table("./data/pml-testing.csv", header = TRUE, sep = ",")
dim(pmlTrain);dim(pmlTest);table(pmlTrain$classe)
```


## 1. linear model. 

### data splitting. 
```{r}
inTrain <- createDataPartition(y=pmlTrain$classe, p=0.7, list=FALSE)
train <- pmlTrain[inTrain, ]
trainCls <- train$classe
test <- pmlTrain[-inTrain,]
testCls <- test$classe
dim(train);dim(test)
```


### Removing the zero and near zero variables. 
```{r}
nzv.train <- nearZeroVar(train)
train<- train[, -nzv]
train$classe <- as.factor(train.small$classe)
dim(train)
```


### Missing value imputation with knnImpute. 
```{r}
prep <- preProcess(train, 
                    method = c("knnImpute"))
train <- predict(prep, newdata = train[, -100])
train <- train[, -c(2, 5)]
```


### feature selection using correlation. 
```{r}
trainCor <- cor(train)
highlyCorrelated <- findCorrelation(trainCor, cutoff=0.75)
train <- train[, -highlyCorrelated]
dim(train)
train <- data.frame(train, classe = trainCls)
str(train)
```


### random forest. 
```{r}
modFit <- train(classe ~ ., data=train, method="rf", prox = TRUE)

```

